name: storeproject
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

